//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aiva.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aiva.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE `ActiveUsers` (
        ///	`ID`	TEXT,
        ///	`JoinedTime`	datetime,
        ///	PRIMARY KEY(`ID`),
        ///	FOREIGN KEY(`ID`) REFERENCES `Users`(`ID`)
        ///); ähnelt.
        /// </summary>
        internal static string ActiveUsers {
            get {
                return ResourceManager.GetString("ActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE `BlacklistedWords` (
        ///	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
        ///	`Word`	TEXT NOT NULL UNIQUE
        ///); ähnelt.
        /// </summary>
        internal static string BlacklistedWords {
            get {
                return ResourceManager.GetString("BlacklistedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE `Chat` (
        ///	`Index`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
        ///	`TwitchID`	TEXT NOT NULL,
        ///	`Timestamp`	datetime NOT NULL,
        ///	`ChatMessage`	text NOT NULL
        ///); ähnelt.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE `Commands` (
        ///	`Index`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
        ///	`Command`	TEXT NOT NULL UNIQUE,
        ///	`Text`	TEXT NOT NULL,
        ///	`CreatedAt`	datetime NOT NULL,
        ///	`ModifiedAt`	datetime,
        ///	`ExecutionRight`	INTEGER NOT NULL DEFAULT 0,
        ///	`Count`	INTEGER DEFAULT 0,
        ///	`Cooldown`	INTEGER DEFAULT 0,
        ///	`LastExecution`	datetime
        ///); ähnelt.
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE `Currency` (
        ///	`ID`	TEXT,
        ///	`Value`	integer NOT NULL,
        ///	PRIMARY KEY(`ID`),
        ///	FOREIGN KEY(`ID`) REFERENCES `Users`(`ID`)
        ///); ähnelt.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE `Timers` (
        ///	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
        ///	`Name`	TEXT NOT NULL UNIQUE,
        ///	`Text`	TEXT NOT NULL,
        ///	`CreatedAt`	datetime NOT NULL,
        ///	`ModifiedAt`	datetime,
        ///	`Interval`	INTEGER NOT NULL DEFAULT 1,
        ///	`NextExecution`	datetime
        ///); ähnelt.
        /// </summary>
        internal static string Timers {
            get {
                return ResourceManager.GetString("Timers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE `TimeWatched` (
        ///	`ID`	TEXT,
        ///	`TimeWatched`	integer NOT NULL,
        ///	PRIMARY KEY(`ID`),
        ///	FOREIGN KEY(`ID`) REFERENCES `Users`(`ID`)
        ///); ähnelt.
        /// </summary>
        internal static string TimeWatched {
            get {
                return ResourceManager.GetString("TimeWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CREATE TABLE `Users` (
        ///	`Id`	TEXT NOT NULL UNIQUE,
        ///	`DisplayName`	TEXT,
        ///	`Name`	TEXT,
        ///	`Type`	TEXT,
        ///	`Bio`	TEXT,
        ///	`CreatedAt`	datetime,
        ///	`UpdatedAt`	datetime,
        ///	`Logo`	TEXT,
        ///	PRIMARY KEY(`Id`)
        ///); ähnelt.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
