//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aiva.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public long IsModerator { get; set; }
        public long TwitchID { get; set; }
        public string Type { get; set; }
        public string CreatedAt { get; set; }
        public string LastSeen { get; set; }
        public Nullable<long> Rank { get; set; }
        public Nullable<long> IsViewing { get; set; }
        public string TimeWatched { get; set; }
    }
}
