//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aiva.Core.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commands
    {
        public long ID { get; set; }
        public Nullable<long> Name { get; set; }
        public long Text { get; set; }
        public long CreatedAt { get; set; }
        public Nullable<long> ModifiedAt { get; set; }
        public long Interval { get; set; }
        public Nullable<long> NextExecution { get; set; }
        public Nullable<long> Count { get; set; }
    }
}
