//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aiva.Core.Storage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StorageEntities : DbContext
    {
        public StorageEntities()
            : base("name=StorageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveUsers> ActiveUsers { get; set; }
        public virtual DbSet<BlacklistedWords> BlacklistedWords { get; set; }
        public virtual DbSet<Commands> Commands { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<TimeWatched> TimeWatched { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<Timers> Timers { get; set; }
    }
}
