//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aiva.Core.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSettings
    {
        public long Index { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    }
}
